version: "3.7"
services:
  mysql:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=strategydb
